#!/bin/bash


battery () {
    battery=$(acpi | sed -n 's/^.*\([0-9][0-9]\).*$/\1/p')
#    echo ${battery}
    if [ ${battery} -lt  20 ] 
    then
        battery="%{B#ffA60000}bat:${battery}%{B-}"   
    else
        battery="bat:${battery}"
    fi
#    echo ${battery}
}


prep () {
    while true; do
        separator=' | '
        desktops=$(python ~/dotfiles/desktops.py)
        title=$(xtitle)
       # battery=$(acpi | sed -n 's/^.*\([0-9][0-9]%\).*$/\1/p')
        volume=$(amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p')
        dateNow=$(date +"%I:%M")
        #echo ${dateNow}
        #battery
        intoBar="%{l}${desktops}%{c}${title}%{r} vol:${volume}${separator}${dateNow}"
        echo ${intoBar}
        sleep .2
    done
}


# background is urxvt tint
# foreground is urxvt yellow
prep | lemonbar -B "#99002b36" -F "#ffB58900" -f "-*-terminus-medium-*-*-*-16-*-*-*-*-*-iso10646-*"

# a nice blue for the foreground, if I wanna switch it up
#7C8AA3

# different blue background
#242A36
