#!/bin/bash


battery () {
    battery=$(acpi | sed -n 's/^.*\([0-9][0-9]\).*$/\1/p')
#    echo ${battery}
    if [ ${battery} -lt  20 ] 
    then
        battery="%{B#ffA60000}bat:${battery}%{B-}"   
    else
        battery="bat:${battery}"
    fi
#    echo ${battery}
}


prep () {
    while true; do
        separator=' | '
        desktops=$(python ~/dotfiles/desktopsHLWM.py $1)
        title=$(xtitle)
       # battery=$(acpi | sed -n 's/^.*\([0-9][0-9]%\).*$/\1/p')
        volume=$(amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p')
        dateNow=$(date +"%I:%M")
        #echo ${dateNow}
        #battery
        intoBar="%{l}${desktops}%{c}${title}%{r} vol:${volume}${separator}${dateNow}   "
        echo ${intoBar}
        sleep .2
    done
}


# background is urxvt tint
# one per monitor, adjust geometry as needed
prep 0 | lemonbar -g 1680x15+0+0 -B "#ff045F70" -F "#ffffffff" -f "-*-terminus-medium-*-*-*-16-*-*-*-*-*-iso10646-*" &
prep 1 | lemonbar -g 1680x15+1680+0 -B "#ff045F70" -F "#ffffffff" -f "-*-terminus-medium-*-*-*-16-*-*-*-*-*-iso10646-*" &
# barScript for bspwm has a few other colors
