#!/bin/bash


battery () {
    battery=$(acpi | sed -n 's/^.*\([0-9][0-9]\).*$/\1/p')
#    echo ${battery}
    if [ ${battery} -lt  20 ] 
    then
        battery="%{B#ffA60000}bat:${battery}%{B-}"   
    else
        battery="bat:${battery}"
    fi
#    echo ${battery}
}


prep () {
    while true; do
        separator=' | '
        desktops=$(python ~/dotfiles/desktopsHLWM.py $1)
        title=$(xtitle)
       # battery=$(acpi | sed -n 's/^.*\([0-9][0-9]%\).*$/\1/p')
        volume=$(amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p')
        timeNow=$(date +"%I:%M")
        dateNow=$(date +"%a %b %d, %Y")
        #echo ${dateNow}
        #battery
        intoBar="%{l}${desktops}%{c}${title}%{r} \uf028 :${volume}${separator} \uf017 ${timeNow}${separator}\uf073 ${dateNow} "
        echo -e ${intoBar}
        sleep .2
    done
}


# background urxvt tint is 045f70, bit darker than this
# one per monitor, adjust geometry as needed
prep 0 | lemonbar  -g 1680x15+0+0 -B "#ff07778c" -F "#ffffffff" -f "FontAwesome:size=10" -f "-*-terminus-medium-*-*-*-12-*-*-*-*-*-iso10646-*" | sh &
prep 1 | lemonbar  -g 1680x15+1680+0 -B "#ff07788C" -F "#ffffffff" -f "FontAwesome:size=10" -f "-*-terminus-medium-*-*-*-12-*-*-*-*-*-iso10646-*" | sh &
# barScript for bspwm has a few other colors
