#!/bin/bash

# how long should the popop stay up?
duration=3

# define geometry
barx=100
bary=0
barw=120
barh=17

# colors

bar_bg='#ff859900' #'#ff242A36'
bar_fg='#ffffffff' #'#ffA7B2C4'

# font used
bar_font='Droid Sans-6'

# put it all together
baropt=" -g ${barw}x${barh}+${barx}+${bary} -B ${bar_bg} -F ${bar_fg} # -f ${bar_font}"

# actually make the popup
(echo " $@"; sleep ${duration}) | lemonbar ${baropt} #-g 120x100+10+10 -B ${bar_bg}
