#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config focused_border_color #000000
bspc config normal_border_color #cccccc
bspc config border_width 3
bspc config urgent_border_color #BD0000

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config top_padding 20

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a firefox desktop=^1
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


feh --bg-scale ~/dotfiles/wallpapers/alley.jpg &
#~/dotfiles/barScript > ~/file.txt &
#compton -c -o 1.0 -i 1.0
xrdb ~/.Xdefaults

